# SPDX-License-Identifier: GPL-3.0-only
"""Create an isolated, unprovisioned development state tree.

This bootstrap prepares paths and environment bindings only. It never creates
identity records, proof material, signing keys, policy authority, or hardware
bindings.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class DevelopmentBootstrapResult:
    root: str
    env_file: str
    marker_file: str
    created_directories: tuple[str, ...]
    provisioned: bool = False
    physical_authority: bool = False

    def to_dict(self) -> dict:
        return {
            "root": self.root,
            "env_file": self.env_file,
            "marker_file": self.marker_file,
            "created_directories": list(self.created_directories),
            "provisioned": self.provisioned,
            "physical_authority": self.physical_authority,
        }


_STATE_DIRECTORIES = (
    "continuity",
    "body",
    "profiles",
    "session",
    "policy",
    "court",
    "execution",
    "receipts",
    "recovery",
)

_ENV_PATHS = {
    "VELVET_CONTINUITY_IDENTITY_PATH": "continuity/identity_chain.json",
    "VELVET_CONTINUITY_PROOF_PATH": "continuity/proof_material.bin",
    "VELVET_SURFACE_METADATA_PATH": "continuity/surface_identity.json",
    "VELVET_BODY_REGISTRY_PATH": "body/registry.json",
    "VELVET_PROFILE_REGISTRY_PATH": "profiles/registry.json",
    "VELVET_SESSION_CONTEXT_PATH": "session/current.json",
    "VELVET_CAPABILITY_CONTEXT_PATH": "policy/capability_context.json",
    "VELVET_CONTINUITY_RECEIPTS_PATH": "receipts/continuity.log",
    "VELVET_COURT_POLICY_PATH": "policy/court_policy.json",
    "VELVET_COURT_SIGNING_KEY_PATH": "court/signing_key.bin",
    "VELVET_EXECUTION_REPLAY_PATH": "execution/consumed_tokens.jsonl",
    "VELVET_EXECUTION_RECEIPTS_PATH": "receipts/execution.log",
}


def bootstrap_development_state(root: str | Path, *, overwrite: bool = False) -> DevelopmentBootstrapResult:
    resolved = Path(root).expanduser().resolve()
    if resolved == Path("/opt/velvet/state"):
        raise ValueError("development bootstrap cannot target the production state root")

    resolved.mkdir(parents=True, exist_ok=True)
    created = []
    for relative in _STATE_DIRECTORIES:
        path = resolved / relative
        path.mkdir(parents=True, exist_ok=True)
        created.append(str(path))

    marker = resolved / "development_state.json"
    env_file = resolved / "velvet-dev.env"
    if not overwrite and (marker.exists() or env_file.exists()):
        raise FileExistsError("development state already exists; use overwrite=True to refresh metadata")

    marker.write_text(
        json.dumps(
            {
                "schema": "velvet.runtime.development-state.v1",
                "state": "development_unprovisioned",
                "production_identity": False,
                "physical_authority": False,
                "write_capable_routes": False,
                "network_listener": False,
            },
            indent=2,
            sort_keys=True,
        ) + "\n",
        encoding="utf-8",
    )

    lines = [
        "# Generated by Velvet Runtime development bootstrap.",
        "# Development paths only. This file grants no authority.",
        "VELVET_RUNTIME_MODE=development",
        "VELVET_PHYSICAL_AUTHORITY=disabled",
    ]
    for name, relative in _ENV_PATHS.items():
        lines.append(f"{name}={resolved / relative}")
    env_file.write_text("\n".join(lines) + "\n", encoding="utf-8")

    return DevelopmentBootstrapResult(
        root=str(resolved),
        env_file=str(env_file),
        marker_file=str(marker),
        created_directories=tuple(created),
    )
