#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-only
set -euo pipefail

RUNTIME_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SERVICE_USER="velvet"
SERVICE_GROUP="velvet"
AUDIO_ENDPOINT=""
TOKEN_SOURCE=""
ENABLE_NOW=0

usage() {
  cat <<'EOF'
Install the separate Founder speech-enabled Runtime systemd posture.

This installer never overwrites, disables, or starts the observation-only
velvet-runtime.service. Enabling speech requires that service to have already
been explicitly stopped and disabled by the operator.

Usage:
  sudo bash scripts/install_up2_speech_systemd.sh \
    --audio-endpoint http://192.168.50.20:8766/v1/speech-expressions \
    --token-file /path/to/audio-speech.token [options]

Required:
  --audio-endpoint URL  Fixed Audio Studio speech endpoint using an IP literal
  --token-file PATH     Existing bearer-token file to install securely

Options:
  --runtime-root PATH   Runtime checkout path under /opt/velvet
  --user NAME           Service user (default: velvet)
  --group NAME          Service group (default: velvet)
  --enable-now          Enable/start only if velvet-runtime.service is disabled
  -h, --help            Show this help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --audio-endpoint)
      AUDIO_ENDPOINT="$2"
      shift 2
      ;;
    --token-file)
      TOKEN_SOURCE="$(readlink -f "$2")"
      shift 2
      ;;
    --runtime-root)
      RUNTIME_ROOT="$(readlink -f "$2")"
      shift 2
      ;;
    --user)
      SERVICE_USER="$2"
      shift 2
      ;;
    --group)
      SERVICE_GROUP="$2"
      shift 2
      ;;
    --enable-now)
      ENABLE_NOW=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ ${EUID} -ne 0 ]]; then
  echo "Run this installer with sudo." >&2
  exit 1
fi

if [[ -z "$AUDIO_ENDPOINT" || -z "$TOKEN_SOURCE" ]]; then
  echo "--audio-endpoint and --token-file are required." >&2
  usage >&2
  exit 2
fi

case "$RUNTIME_ROOT" in
  /opt/velvet/*)
    ;;
  *)
    echo "Refusing Runtime root outside /opt/velvet: $RUNTIME_ROOT" >&2
    exit 1
    ;;
esac

for required in \
  "$RUNTIME_ROOT/velvet_cli.py" \
  "$RUNTIME_ROOT/.venv/bin/python" \
  "$RUNTIME_ROOT/.velvet-dev/env.sh" \
  "$RUNTIME_ROOT/scripts/validate_speech_endpoint.py" \
  "$RUNTIME_ROOT/deploy/systemd/velvet-runtime-speech.service.in"; do
  if [[ ! -e "$required" ]]; then
    echo "Required path is missing: $required" >&2
    exit 1
  fi
done

if [[ ! -f "$TOKEN_SOURCE" ]]; then
  echo "Bearer-token source is not a regular file: $TOKEN_SOURCE" >&2
  exit 1
fi

if ! "$RUNTIME_ROOT/.venv/bin/python" - "$TOKEN_SOURCE" <<'PY'
from pathlib import Path
import sys

text = Path(sys.argv[1]).read_text(encoding="utf-8").strip()
if not text or "\n" in text or "\r" in text:
    raise SystemExit(1)
PY
then
  echo "Bearer-token file must contain one non-empty text token." >&2
  exit 1
fi

NORMALIZED_ENDPOINT="$(
  "$RUNTIME_ROOT/.venv/bin/python" \
    "$RUNTIME_ROOT/scripts/validate_speech_endpoint.py" \
    --endpoint "$AUDIO_ENDPOINT" --field endpoint
)"
AUDIO_HOST="$(
  "$RUNTIME_ROOT/.venv/bin/python" \
    "$RUNTIME_ROOT/scripts/validate_speech_endpoint.py" \
    --endpoint "$AUDIO_ENDPOINT" --field host
)"

if ! getent group "$SERVICE_GROUP" >/dev/null; then
  groupadd --system "$SERVICE_GROUP"
fi

if ! id "$SERVICE_USER" >/dev/null 2>&1; then
  useradd \
    --system \
    --gid "$SERVICE_GROUP" \
    --home-dir /nonexistent \
    --shell /usr/sbin/nologin \
    "$SERVICE_USER"
fi

install -d -m 0755 -o root -g root /opt/velvet
install -d -m 0700 -o "$SERVICE_USER" -g "$SERVICE_GROUP" /opt/velvet/state
install -d -m 0700 -o "$SERVICE_USER" -g "$SERVICE_GROUP" /opt/velvet/state/audio
chown -R "$SERVICE_USER:$SERVICE_GROUP" "$RUNTIME_ROOT/.velvet-dev"

install -d -m 0750 -o root -g "$SERVICE_GROUP" /etc/velvet
install -m 0640 -o root -g "$SERVICE_GROUP" \
  "$TOKEN_SOURCE" /etc/velvet/audio-speech.token

ENV_PATH=/etc/velvet/runtime-speech.env
cat > "$ENV_PATH" <<EOF
# Generated by install_up2_speech_systemd.sh
VELVET_AUDIO_SPEECH_ENDPOINT=$NORMALIZED_ENDPOINT
VELVET_AUDIO_SPEECH_EGRESS_DB=/opt/velvet/state/audio/speech-egress.sqlite3
VELVET_AUDIO_SPEECH_TOKEN_FILE=/etc/velvet/audio-speech.token
VELVET_AUDIO_SPEECH_TIMEOUT_SECONDS=0.75
VELVET_AUDIO_SPEECH_MAX_PENDING=256
EOF
chown root:"$SERVICE_GROUP" "$ENV_PATH"
chmod 0640 "$ENV_PATH"

SERVICE_PATH=/etc/systemd/system/velvet-runtime-speech.service
sed \
  -e "s|@RUNTIME_ROOT@|$RUNTIME_ROOT|g" \
  -e "s|@SERVICE_USER@|$SERVICE_USER|g" \
  -e "s|@SERVICE_GROUP@|$SERVICE_GROUP|g" \
  -e "s|@AUDIO_HOST@|$AUDIO_HOST|g" \
  "$RUNTIME_ROOT/deploy/systemd/velvet-runtime-speech.service.in" \
  > "$SERVICE_PATH"
chmod 0644 "$SERVICE_PATH"

systemd-analyze verify "$SERVICE_PATH"
systemctl daemon-reload

printf '[Velvet] Installed %s\n' "$SERVICE_PATH"
printf '[Velvet] Audio endpoint: %s\n' "$NORMALIZED_ENDPOINT"
printf '[Velvet] Allowed Audio IP only: %s\n' "$AUDIO_HOST"
printf '[Velvet] Physical authority remains disabled.\n'
printf '[Velvet] Observation-only velvet-runtime.service was not changed.\n'

if [[ "$ENABLE_NOW" -eq 1 ]]; then
  if systemctl is-active --quiet velvet-runtime.service; then
    echo "Refusing startup while velvet-runtime.service is active." >&2
    echo "Stop and disable that proof service explicitly, then rerun." >&2
    exit 1
  fi
  if systemctl is-enabled --quiet velvet-runtime.service 2>/dev/null; then
    echo "Refusing startup while velvet-runtime.service remains enabled." >&2
    echo "Disable the proof service explicitly before enabling speech posture." >&2
    exit 1
  fi
  systemctl enable --now velvet-runtime-speech.service
  systemctl --no-pager --full status velvet-runtime-speech.service
else
  cat <<EOF
[Velvet] Speech service was not started automatically.
[Velvet] Review the generated unit and environment first.
[Velvet] To change posture deliberately:
  sudo systemctl disable --now velvet-runtime.service
  sudo systemctl enable --now velvet-runtime-speech.service
  sudo "$RUNTIME_ROOT/.venv/bin/python" "$RUNTIME_ROOT/scripts/up2_speech_service_validate.py" \
    --audio-host "$AUDIO_HOST"
EOF
fi
